### ISSUE TITLE
Does not work with unscaled time.

### ISSUE THREAD

**Issue by WazWaz** [Nickk888SAMP/RTSCameraController-Cinemachine#1]
If Time.timeScale is changed, the interaction scales too. In particular this means the camera will not work when Time.timeScale is set to zero (the normal way to Pause in Unity).

Fix is to use Time.unscaledDeltaTime throughout, including as additional parameter to Mathf.SmoothDamp(..., float.PositiveInfinity, Time.unscaledDeltaTime).

It could be an option, or it could just honour CinemachineBrain.IgnoreTimeScale.

**Comment by Nickk888SAMP** [comment]
Hey! Thank you for noticing! I've fixed the issue and drafted a new release :)

**Comment by WazWaz** [comment]
The shipped prefab has the new option set to time-independent (which I think is the right default) but its MainCamera CinemachineBrain set to time-dependent.

**Comment by Nickk888SAMP** [comment]
You are right! After some testing there's indeed an issue with time scale and the camera settings (Noise, Damping etc.).
I've fixed the issue and pushed the changes to the repo.

I'm waiting for you to make a pull request for #2 So i can apply all the changes and draft a release.
