### ISSUE TITLE
The Rotation attribute of the Main Camera keeps changing in the static state

### ISSUE THREAD

**Issue by NetCodersX** [Nickk888SAMP/RTSCameraController-Cinemachine#3]
This causes the camera to shake up and down, left and right

**Comment by Nickk888SAMP** [comment]
Can you explain a little more? What do you mean by "Static state"? How can i reproduce this?

**Comment by NetCodersX** [comment]
> Can you explain a little more? What do you mean by "Static state"? How can i reproduce this?

The state when there is no movement operation.

**Comment by Nickk888SAMP** [comment]
Do you mean the soft movement of the camera? This is a feature of cinemachine called "Noise" it makes the camera move and rotate softly, it's actually a feature not a bug, you can disable this if you don't like the effect in the settings of the Cinemachine Virtual Camera. In the "Noise" section change it to "none"

**Comment by NetCodersX** [comment]
> Do you mean the soft movement of the camera? This is a feature of cinemachine called "Noise" it makes the camera move and rotate softly, it's actually a feature not a bug, you can disable this if you don't like the effect in the settings of the Cinemachine Virtual Camera. In the "Noise" section change it to "none"

Thanks for the answer,
Will this project update other functions in the future?

**Comment by Nickk888SAMP** [comment]
Probably, when i get any ideas, of course if you are a developer, you can collaborate if you want :)
